# Generated by Django 4.0.5 on 2022-06-13 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, default='/placeholder.jpg', null=True, upload_to='')),
            ],
        ),
    ]
